### PR TITLE
Full pull request

### PR DESCRIPTION
**Pull request by mominabbass**
Respected Neil,

I hope you are well. We wanted to let you know that we are submitting a pull request to update our paper. We contacted the ICML 2022 Publication Chair, Gang Niu, about this (through Tianyi Chen) after which we were granted the permission to make a full pull request to update our paper (please find below the email screenshots). While finalizing our github, we found an error in our testing script. Now we have updated the implementation of our code in the GitHub link and also updated the results in the revised ICML paper. We would be very appreciative if you can help us with the process of updating our paper. Thank you!

Email from Gang Niu:
Gang_Niu_1
Gang_Niu_2

Revised paper:
[abbas22b.pdf](https://github.com/mlresearch/v162/files/9277007/abbas22b.pdf)

Kind regards,
Momin Abbas

### CODE REVIEW

**Comment by lawrennd** [comment]
Thank you, but it looks like you didn’t change the PDF in this pull request.

**Comment by mominabbass** [comment]
Hi Neil,
I apologize for that. I am not very adept at using the GitHub platform. I had changed the PDF in the forked repository but somehow the change was not detected in the pull request. I just sent a pull request to update the PDF.
Should you have any other concerns, please feel free to contact me. Thank you.
Kind regards,Momin Abbas
    On Sunday, August 7, 2022 at 11:36:51 AM EDT, Neil Lawrence ***@***.***> wrote:  
 
 


Thank you, but it looks like you didn’t change the PDF in this pull request.

**Comment by mominabbass** [comment]
> Thank you, but it looks like you didn’t change the PDF in this pull request.

Hi Neil. I hope you are well. This is a follow up comment regarding the pull request. Kindly let us know if there is an update. Thank you.

Kind regards,
Momin Abbas

**Comment by mominabbass** [comment]
Respected ICML organizers,

We submitted this pull request about a week ago but the files have not been updated yet. Can you kindly update the files we included in this pull request or give an estimate of the time it requires to do so. We would appreciate it. Thank you.

Kind regards,
Momin Abbas

**Review by lawrennd — APPROVED** [review]

**Pull request merged**
