### PR TITLE
fixing a name spelling error inside the PDF - publication file

### PR DESCRIPTION
**Pull request by baogiadoan**
Query: could you please help to fix a name spelling error inside the PDF - publication file

Damith C. Ranashinghe (last author) should be Damith C. Ranasinghe

This query has been approved by Professor Neil Lawrence.

### CODE REVIEW

**Review by lawrennd — APPROVED** [review]
You need to submit an updated PDF via pull request. Approving this change of intitials.

**Comment by baogiadoan** [comment]
thanks Professor Neil Lawrence, I will submit another pull request with an attached PDF file.

**Comment by baogiadoan** [comment]
thanks Professor Neil Lawrence, hereby I attached the revised version with the correct name spelling
[doan22a_rev1.pdf](https://github.com/mlresearch/v162/files/10159345/doan22a_rev1.pdf)

**Comment by baogiadoan** [comment]
I also submitted another pull request for your convenience. Thank you!

**Pull request merged**
