### PR TITLE
Update 2022-06-28-kim22j.md

### PR DESCRIPTION
**Pull request by junghunkim7786**
Hello. I'm one of the authors of the paper 'rotting infinitely many armed bandits'. I found that there are tex command errors in our abstract. I would like to modify them (\rot -> \varrho) in the abstract.

### CODE REVIEW

**Comment by junghunkim7786** [comment]
I would like to attach a screenshot including the command errors below.
error

**Review by lawrennd — APPROVED** [review]
Thanks Jung Hun!

**Comment by junghunkim7786** [comment]
Thank you so much. I appreciate it!

**Comment by lawrennd** [comment]
No problem Jung Hun, thanks for the fix!

**Pull request merged**
